# github action (workflow) to perform continuous integration
name: CI

# control when the action will run
on:
  # trigger the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# a workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow contains a single job called "test"
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    # a strategy allows to run the same job with different combinations of options
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # the caret (^) mans to use the latest minor revision of the 1.5.x version
        version: ['^1.5','^1.6']

    # the type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout the git repository into the VM
      - uses: actions/checkout@v2
      # install julia into the VM
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
      # build the Lebedev package
      - uses: julia-actions/julia-buildpkg@latest
      # run tests for the Lebedev package
      - uses: julia-actions/julia-runtest@latest
      # upload report to codecov.io
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
